import { DefinitionBaseDescription } from "./DefinitionBaseDescription";
import { GridColumnAnimationSettingsDescription } from "./GridColumnAnimationSettingsDescription";
import { ColumnFilterConditionDescription } from "./ColumnFilterConditionDescription";
import { Type } from "./type";
/**
 * @hidden
 */
export declare abstract class ColumnDescription extends DefinitionBaseDescription {
    static $t: Type;
    protected get_type(): string;
    constructor();
    private br;
    paddingLeft: number;
    private bt;
    paddingTop: number;
    private bs;
    paddingRight: number;
    private bq;
    paddingBottom: number;
    private b1;
    name: string;
    private b2;
    propertyPath: string;
    private b0;
    headerText: string;
    private by;
    actualHeaderText: string;
    private b3;
    selectedBackground: string;
    private bz;
    actualSelectedBackground: string;
    private bc;
    animationSettings: GridColumnAnimationSettingsDescription;
    private bo;
    minWidth: number;
    private bg;
    isFromMarkup: boolean;
    private be;
    isAutoGenerated: boolean;
    private ba;
    filter: ColumnFilterConditionDescription;
    private bf;
    isFilteringEnabled: boolean;
    private bh;
    isHidden: boolean;
    private bi;
    shouldRemoveWhenHidden: boolean;
    private b4;
    sortDirection: string;
}
