import { Description } from "./Description";
import { Type } from "./type";
/**
 * @hidden
 */
export declare abstract class DefinitionBaseDescription extends Description {
    static $t: Type;
    protected get_type(): string;
    readonly type: string;
    constructor();
    private ab;
    background: string;
    private ac;
    border: string;
    private v;
    actualBorder: string;
    private n;
    borderLeftWidth: number;
    private p;
    borderTopWidth: number;
    private o;
    borderRightWidth: number;
    private m;
    borderBottomWidth: number;
    private u;
    actualBackground: string;
    private ak;
    stickyRowBackground: string;
    private z;
    actualStickyRowBackground: string;
    private aj;
    pinnedRowBackground: string;
    private y;
    actualPinnedRowBackground: string;
    private ah;
    lastStickyRowBackground: string;
    private w;
    actualLastStickyRowBackground: string;
    private g;
    contentOpacity: number;
    private ag;
    horizontalAlignment: string;
    private am;
    verticalAlignment: string;
    private ai;
    lineBreakMode: string;
    private x;
    actualLineBreakMode: string;
    private al;
    textColor: string;
    private aa;
    actualTextColor: string;
    private h;
    pinnedRowOpacity: number;
    private f;
    actualPinnedRowOpacity: number;
    private _fontFamily;
    fontFamily: string;
    private _fontSize;
    fontSize: number;
    private _fontStyle;
    fontStyle: string;
    private _fontWeight;
    fontWeight: string;
    private ae;
    DataBindingRef: string;
    private af;
    DataBoundRef: string;
    private ad;
    CellStyleKeyRequestedRef: string;
}
