import { AnnotationLayerDescription } from "./AnnotationLayerDescription";
import { Type } from "./type";
/**
 * @hidden
 */
export declare class CalloutLayerDescription extends AnnotationLayerDescription {
    static $t: Type;
    protected get_type(): string;
    constructor();
    private c2;
    labelMemberPath: string;
    private c5;
    xMemberPath: string;
    private c6;
    yMemberPath: string;
    private c1;
    keyMemberPath: string;
    private b3;
    isCalloutOffsettingEnabled: boolean;
    private c0;
    contentMemberPath: string;
    private c3;
    targetSeriesRef: string;
    private cz;
    collisionChannel: string;
    private b2;
    isAutoCalloutBehaviorEnabled: boolean;
    private b5;
    useValueForAutoCalloutLabels: boolean;
    private b4;
    isCustomCalloutStyleEnabled: boolean;
    private cm;
    autoCalloutLabelPrecision: number;
    private cy;
    calloutTextColor: string;
    private cq;
    calloutBackground: string;
    private cn;
    calloutInterpolatedValuePrecision: number;
    private cv;
    calloutOutline: string;
    private cu;
    calloutLeaderBrush: string;
    private cb;
    calloutPaddingLeft: number;
    private cd;
    calloutPaddingTop: number;
    private cc;
    calloutPaddingRight: number;
    private ca;
    calloutPaddingBottom: number;
    private cr;
    calloutCollisionMode: string;
    private ce;
    calloutPositionPadding: number;
    private cf;
    calloutStrokeThickness: number;
    private c4;
    textStyle: string;
    private cx;
    CalloutStyleUpdatingRef: string;
    private cs;
    CalloutContentUpdatingRef: string;
    private ct;
    CalloutLabelUpdatingRef: string;
    private cw;
    CalloutSeriesSelectingRef: string;
}
