import { AnnotationLayerDescription } from "./AnnotationLayerDescription";
import { Type } from "./type";
/**
 * @hidden
 */
export declare class CrosshairLayerDescription extends AnnotationLayerDescription {
    static $t: Type;
    protected get_type(): string;
    constructor();
    private cw;
    horizontalLineStroke: string;
    private cz;
    verticalLineStroke: string;
    private cy;
    targetSeriesRef: string;
    private b4;
    useInterpolation: boolean;
    private b2;
    isAxisAnnotationEnabled: boolean;
    private c3;
    xAxisAnnotationTextColor: string;
    private c1;
    xAxisAnnotationBackground: string;
    private cs;
    xAxisAnnotationInterpolatedValuePrecision: number;
    private c2;
    xAxisAnnotationOutline: string;
    private b9;
    xAxisAnnotationPaddingLeft: number;
    private cb;
    xAxisAnnotationPaddingTop: number;
    private ca;
    xAxisAnnotationPaddingRight: number;
    private b8;
    xAxisAnnotationPaddingBottom: number;
    private ce;
    yAxisAnnotationPaddingLeft: number;
    private cg;
    yAxisAnnotationPaddingTop: number;
    private cf;
    yAxisAnnotationPaddingRight: number;
    private cd;
    yAxisAnnotationPaddingBottom: number;
    private cc;
    xAxisAnnotationStrokeThickness: number;
    private c6;
    yAxisAnnotationTextColor: string;
    private c4;
    yAxisAnnotationBackground: string;
    private ct;
    yAxisAnnotationInterpolatedValuePrecision: number;
    private c5;
    yAxisAnnotationOutline: string;
    private ch;
    yAxisAnnotationStrokeThickness: number;
    private c0;
    verticalLineVisibility: string;
    private cx;
    horizontalLineVisibility: string;
    private b3;
    skipUnknownValues: boolean;
}
