import { Description } from "./Description";
import { Type } from "./type";
/**
 * @hidden
 */
export declare abstract class RingSeriesBaseDescription extends Description {
    static $t: Type;
    private a4;
    tooltipTemplateRef: string;
    private aj;
    dataSourceRef: string;
    private aw;
    legendRef: string;
    private ak;
    fontFamily: string;
    private l;
    fontSize: number;
    private am;
    fontWeight: string;
    private al;
    fontStyle: string;
    protected get_type(): string;
    readonly type: string;
    constructor();
    private a5;
    valueMemberPath: string;
    private ap;
    labelMemberPath: string;
    private av;
    legendLabelMemberPath: string;
    private aq;
    labelsPosition: string;
    private au;
    leaderLineVisibility: string;
    private ar;
    leaderLineFill: string;
    private as;
    leaderLineStroke: string;
    private p;
    leaderLineStrokeThickness: number;
    private o;
    leaderLineOpacity: number;
    private at;
    leaderLineType: string;
    private n;
    leaderLineMargin: number;
    private s;
    othersCategoryThreshold: number;
    private a0;
    othersCategoryType: string;
    private az;
    othersCategoryText: string;
    private an;
    formatLabelRef: string;
    private ao;
    formatLegendLabelRef: string;
    private m;
    labelExtent: number;
    private w;
    startAngle: number;
    private ax;
    othersCategoryFill: string;
    private ay;
    othersCategoryStroke: string;
    private r;
    othersCategoryStrokeThickness: number;
    private q;
    othersCategoryOpacity: number;
    private a2;
    selectedSliceFill: string;
    private a3;
    selectedSliceStroke: string;
    private v;
    selectedSliceStrokeThickness: number;
    private u;
    selectedSliceOpacity: number;
    private f;
    brushes: string[];
    private g;
    outlines: string[];
    private j;
    isSurfaceInteractionDisabled: boolean;
    private t;
    radiusFactor: number;
    private a1;
    PropertyUpdatedRef: string;
}
