import { Base, Point, Type, INotifyPropertyChanged, PropertyChangedEventArgs } from "./type";
import { DomRenderer, DomWrapper } from "./dom";
import { CanvasGestureDOMEventProxy } from "./CanvasGestureDOMEventProxy";
import { Brush } from "./Brush";
import { Key } from "./Key";
import { IScrollerKeyboardListener } from "./IScrollerKeyboardListener";
import { ScrollerScrollingEventArgs } from "./ScrollerScrollingEventArgs";
/**
 * @hidden
 */
export declare class ScrollerView extends Base {
    static $t: Type;
    constructor(a: Scroller);
    b: Scroller;
    protected x: DomRenderer;
    protected ab: DomWrapper;
    ay(): Brush;
    protected w: HTMLDivElement;
    protected a: CanvasGestureDOMEventProxy;
    aa: DomWrapper;
    y: DomWrapper;
    z: DomWrapper;
    ac: DomWrapper;
    ar(a: any): void;
    private j;
    private n;
    private ae;
    private af;
    private ag;
    private l;
    private m;
    private d;
    private i;
    ap(a: number): void;
    aq(a: number): void;
    an(a: number): void;
    ao(a: number): void;
    ad(): void;
    private ah;
    private ai;
    aw(a: number): void;
    private aj;
    u(): number;
    v(): number;
    private k;
    av(a: number): void;
    as(a: any): void;
    private c;
    at(a: () => void): void;
    private h;
    private g;
    private s;
    private p;
    private t;
    private q;
    private f;
    private e;
    private r;
    private o;
    am(): void;
    al(): void;
    ax(a: number, b: number): void;
    au(a: number, b: number): void;
    ak(): void;
}
/**
 * @hidden
 */
export declare class Scroller extends Base implements INotifyPropertyChanged {
    static $t: Type;
    constructor();
    private aq;
    smallVerticalChange: number;
    private _keyboardListener;
    keyboardListener: IScrollerKeyboardListener;
    private ai;
    largeVerticalChange: number;
    private ad;
    ay: number;
    private ab;
    aw: number;
    private ap;
    smallHorizontalChange: number;
    private ah;
    largeHorizontalChange: number;
    private ac;
    ax: number;
    private aa;
    av: number;
    private ag;
    contentWidth: number;
    private aj;
    minScrollbarSize: number;
    private am;
    scrollbarSpan: number;
    q(a: Key, b: boolean, c: boolean): boolean;
    private w;
    private o;
    private p;
    private v;
    private r;
    private x;
    private n;
    private u;
    private t;
    private ar;
    verticalTrackStartInset: number;
    private cf;
    scrollbarBrush: Brush;
    private b2;
    private k;
    private y;
    protected b5(a: string, b: any, c: any): void;
    private af;
    contentHeight: number;
    b3(a: number): void;
    b1(a: number): void;
    b4(a: number, b: number): void;
    private at;
    viewportWidth: number;
    private as;
    viewportHeight: number;
    private ao;
    scrollTop: number;
    private an;
    scrollLeft: number;
    private c;
    readonly view: ScrollerView;
    provideContainer(a: any): void;
    provideContent(a: any): void;
    s(a: Point, b: number): boolean;
    private i;
    lockScrollDirection: boolean;
    l: boolean;
    private ae;
    actualVerticalScrollbarHeight: number;
    private z;
    actualHorizontalScrollbarWidth: number;
    private h;
    private f;
    private g;
    private ch;
    private e;
    propertyChanged: (sender: any, e: PropertyChangedEventArgs) => void;
    focus(): void;
    b0(a: Point): void;
    bz(a: Point): void;
    onScrolling: (sender: any, args: ScrollerScrollingEventArgs) => void;
    scrollTo(a: number, b: number): void;
    private ak;
    private al;
    private b9;
    private j;
    private b8;
    private cb;
    private ce;
    private cc;
    private cd;
    by(a: Point): void;
}
