import { Description } from "./Description";
import { Type } from "./type";
/**
 * @hidden
 */
export declare abstract class SeriesDescription extends Description {
    static $t: Type;
    protected get_type(): string;
    readonly type: string;
    constructor();
    private az;
    legendItemVisibility: string;
    private ax;
    legendItemBadgeTemplateRef: string;
    private ay;
    legendItemTemplateRef: string;
    private av;
    discreteLegendItemTemplateRef: string;
    private a5;
    transitionEasingFunctionRef: string;
    private a6;
    transitionInEasingFunctionRef: string;
    private al;
    transitionDuration: number;
    private x;
    resolution: number;
    private as;
    brush: string;
    private ap;
    actualBrush: string;
    private a0;
    outline: string;
    private ar;
    actualOutline: string;
    private ab;
    thickness: number;
    private i;
    isHighlightingEnabled: boolean;
    private h;
    isDropShadowEnabled: boolean;
    private y;
    shadowBlur: number;
    private a2;
    shadowColor: string;
    private l;
    useSingleShadow: boolean;
    private z;
    shadowOffsetX: number;
    private aa;
    shadowOffsetY: number;
    private u;
    areaFillOpacity: number;
    private t;
    actualAreaFillOpacity: number;
    private g;
    isDefaultToolTipSelected: boolean;
    private k;
    showDefaultTooltip: boolean;
    private am;
    transitionInDuration: number;
    private a7;
    transitionInSpeedType: string;
    private j;
    mouseOverEnabled: boolean;
    private at;
    coercionMethodsRef: string;
    private f;
    expectFunctions: boolean;
    private aw;
    hitTestMode: string;
    private aq;
    actualHitTestMode: string;
    private v;
    finalValue: number;
    private w;
    percentChange: number;
    private a1;
    RenderRequestedRef: string;
    private a4;
    tooltipTemplateRef: string;
    private au;
    dataSourceRef: string;
    private a3;
    title: string;
}
